name: queue_ease
description: 'QueueEase - Smart queue management for businesses and customers.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^15.1.2

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.7
  firebase_crashlytics: ^4.3.5

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0

  # Testing
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

  # Native splash
  flutter_native_splash: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700

